import sys
sys.stdout.reconfigure(encoding='utf-8')

R='\033[0m'; B='\033[1m'
RED='\033[91m'; GRN='\033[92m'; YEL='\033[93m'; BLU='\033[94m'; MAG='\033[95m'; CYN='\033[96m'; GRY='\033[90m'; WHT='\033[97m'
BLK='\033[30m'
BG_R='\033[41m'; BG_G='\033[42m'; BG_Y='\033[43m'; BG_B='\033[44m'; BG_M='\033[45m'; BG_PK='\033[105m'

print(f'{B}{CYN}╭─────────────────────────────────────────────────────────────╮{R}')
print(f'{B}{CYN}│  {WHT}--2 VISUAL PLAN — BLOAT MAP (glance-friendly colors){CYN}        │{R}')
print(f'{B}{CYN}╰─────────────────────────────────────────────────────────────╯{R}')
print()
print(f'{B}{RED}█████ DELETE ZONE ████████████████████████████████████████████{R}')
print()
print(f' {B}{BG_R}{WHT} ① DEBUG PILE-UP        {R}  {RED}▓▓▓▓▓▓▓▓▓▓{R}  {B}{RED}5 skills{R}')
print(f'   {RED}c-debug · c-mega-debug · c-gen2-debug{R}')
print(f'   {RED}c-deploy-bug-check · c-churn{R}')
print(f'   {GRY}→ keep 1, archive 4{R}')
print()
print(f' {B}{BG_M}{WHT} ② SUPERSEDED OLD       {R}  {MAG}▓▓▓▓▓▓▓▓{R}    {B}{MAG}4 skills{R}')
print(f'   {MAG}c9-1-voice {GRY}(→ c-voice){R}')
print(f'   {MAG}c9-2-pass-throughA · c9-2-pass-throughB{R}')
print(f'   {MAG}movie-trailer-test {GRY}(→ movie-trailer-go){R}')
print()
print(f' {B}{BG_Y}{BLK} ③ ONE-SHOT TESTS       {R}  {YEL}▓▓▓▓▓▓{R}      {B}{YEL}5 skills{R}')
print(f'   {YEL}dashboard-demo · qquick · tp-link-debug{R}')
print(f'   {YEL}claude-2 · c-claude-term-creations{R}')
print()
print(f' {B}{BG_B}{WHT} ④ DASHBOARD SUB-SKILLS {R}  {BLU}▓▓▓▓▓{R}       {B}{BLU}5 skills{R}')
print(f'   {BLU}dashboard--client-database · --communication{R}')
print(f'   {BLU}--css · --effects-and-travel · --support{R}')
print(f'   {GRY}→ roll into parent dashboard{R}')
print()
print(f' {B}{BG_PK}{WHT} ⑤ MCP SERVERS          {R}  {MAG}▓▓▓{R}         {B}{MAG}3 servers{R}')
print(f'   {MAG}Gmail · Google Calendar · PayPal{R}')
print()
print(f' {B}{BG_R}{WHT} ⑥ STALE MEMORY FILES   {R}  {RED}▓▓▓▓{R}        {B}{RED}~7 files{R}')
print(f'   {RED}mega-export-2026-03-23 · job3/4/5 prep{R}')
print(f'   {RED}wing-dashboard-export-prompt · wing-input-shimmer{R}')
print(f'   {RED}torok-streams {GRY}(if unused){R}')
print()
print(f'{B}{GRN}█████ KEEP-CORE ██████████████████████████████████████████████{R}')
print()
print(f' {B}{BG_G}{BLK} 🔒 SHORTCUTS           {R}  {GRN}--0 through --9{R}')
print(f' {B}{BG_G}{BLK} 🔒 TONE + OUTPUT LOCK  {R}  {GRN}per-output-master{R}')
print(f' {B}{BG_G}{BLK} 🔒 COMMS PREFERENCES   {R}  {GRN}no-pet-names · cache-buster · glossary{R}')
print(f' {B}{BG_G}{BLK} 🔒 ACTIVE JOBS         {R}  {GRN}Wing Dash · Railroad · Scout Troop{R}')
print(f' {B}{BG_G}{BLK} 🔒 PRIVATE JOURNAL     {R}  {GRN}chad-private.md{R}')
print(f' {B}{BG_G}{BLK} 🔒 TOP ~20 SKILLS      {R}  {GRN}c-tone · c-skills · c-notify · c-railgun{R}')
print(f'                            {GRN}c-voice · c-netlify · jset · go · dashboard{R}')
print()
print(f'         {B}{RED}╔══════════╗{R}                {B}{GRN}╔══════════╗{R}')
print(f'         {B}{RED}║ BEFORE   ║{R}                {B}{GRN}║  AFTER   ║{R}')
print(f'         {B}{RED}║ 80 skill ║{R}    {B}{CYN}──→{R}         {B}{GRN}║ 20 skill ║{R}')
print(f'         {B}{RED}║ 30 mem   ║{R}                {B}{GRN}║ 12 mem   ║{R}')
print(f'         {B}{RED}║ 3 MCPs   ║{R}                {B}{GRN}║ 0 MCPs   ║{R}')
print(f'         {B}{RED}╚══════════╝{R}                {B}{GRN}╚══════════╝{R}')
print(f'           {B}{RED}BLOATED{R}                      {B}{GRN}LEAN ⚡{R}')
print()
print(f'{B}{BG_R}{WHT} red {R}=delete  {B}{BG_M}{WHT} purple {R}=superseded  {B}{BG_Y}{BLK} yellow {R}=one-shot  {B}{BG_B}{WHT} blue {R}=roll-up  {B}{BG_PK}{WHT} pink {R}=MCPs  {B}{BG_G}{BLK} green {R}=keep')
