const mediaData = {
    "Top 20 Overall": [
        { "name": "CNN (Entertainment)", "reach": "300 million monthly", "label": "major", "color": "#CC0000", "vibe": "broadcast-studio", "pId": "N_q_f_T-O_M", "url": "https://www.cnn.com/entertainment" },
        { "name": "BBC (Entertainment & Arts)", "reach": "150 million monthly", "label": "bin", "color": "#E91802", "vibe": "london-skyline", "pId": "v8S-UaE16C8", "url": "https://www.bbc.com/culture" },
        { "name": "The New York Times", "reach": "150 million monthly", "label": "pola6", "color": "#121212", "vibe": "printing-press", "pId": "E9reH_x_y-8", "url": "https://www.nytimes.com/section/arts" },
        { "name": "Forbes", "reach": "90 million monthly", "label": "pola6", "color": "#DC0000", "vibe": "office-skyscraper", "pId": "m_HRR_fV76fM", "url": "https://www.forbes.com/entertainment" },
        { "name": "Bloomberg", "reach": "90 million monthly", "label": "pola6", "color": "#2800D7", "vibe": "data-center", "pId": "W_XG_Gf_V7fM", "url": "https://www.bloomberg.com/entertainment" },
        { "name": "The Washington Post", "reach": "90 million monthly", "label": "pola6", "color": "#231F20", "vibe": "dc-monument", "pId": "nO_g9p_yXyA", "url": "https://www.washingtonpost.com/entertainment" },
        { "name": "The Guardian", "reach": "60 million monthly", "label": "pola6", "color": "#052962", "vibe": "blue-texture", "pId": "p5P-wI_w-R4", "url": "https://www.theguardian.com/culture" },
        { "name": "Business Insider", "reach": "60 million monthly", "label": "pola6", "color": "#003058", "vibe": "skyscraper-office", "pId": "YmX_K4eBwH8", "url": "https://www.businessinsider.com/entertainment" },
        { "name": "Los Angeles Times", "reach": "30 million monthly", "label": "presentation", "color": "#000000", "vibe": "palm-trees-sunset", "pId": "uPKY_p470d0", "url": "https://www.latimes.com/entertainment" },
        { "name": "Variety", "reach": "25 million monthly", "label": "minias", "color": "#DA291C", "vibe": "red-carpet-event", "pId": "p31_w-yXyA", "url": "https://variety.com" },
        { "name": "Billboard", "reach": "25 million monthly", "label": "housecreatory v11", "color": "#111111", "vibe": "music-awards-ceremony", "pId": "E9reH_x_y-8", "url": "https://www.billboard.com" },
        { "name": "The Hollywood Reporter", "reach": "15 million monthly", "label": "minias", "color": "#956E37", "vibe": "film-reel", "pId": "H02zMhJ4T9c", "url": "https://www.hollywoodreporter.com" },
        { "name": "Rolling Stone", "reach": "15 million monthly", "label": "housecreatory v11", "color": "#DF1F26", "vibe": "rock-concert-grit", "pId": "K_x_y-8XyA", "url": "https://www.rollingstone.com" },
        { "name": "Complex", "reach": "15 million monthly", "label": "delicreations v11", "color": "#111111", "vibe": "urban-graffiti", "pId": "n8mG9K_wUeU", "url": "https://www.complex.com" },
        { "name": "Vulture (NY Mag)", "reach": "10 million monthly", "label": "minias", "color": "#EF3E36", "vibe": "theater-curtain-pink", "pId": "vXz7w3B80yE", "url": "https://www.vulture.com" },
        { "name": "Entertainment Weekly", "reach": "10 million monthly", "label": "sx", "color": "#ED1C24", "vibe": "pop-culture-bokeh", "pId": "O_g9p_yXyA", "url": "https://ew.com" },
        { "name": "Pitchfork", "reach": "5 million monthly", "label": "delicreations", "color": "#6E57ED", "vibe": "vinyl-stage", "pId": "V_yXyA-8XyA", "url": "https://pitchfork.com" },
        { "name": "NME", "reach": "5 million monthly", "label": "delicreations", "color": "#ED1C24", "vibe": "punk-rock-grit", "pId": "N_yXyA_yXyA", "url": "https://www.nme.com" },
        { "name": "Vibe", "reach": "3 million monthly", "label": "minias", "color": "#000000", "vibe": "hip-hop-club", "pId": "H_yXyA_yXyA", "url": "https://www.vibe.com" },
        { "name": "The FADER", "reach": "3 million monthly", "label": "delicreations v11", "color": "#222222", "vibe": "aesthetic-shadow", "pId": "pG_y5j9XQW0", "url": "https://www.thefader.com" }
    ],

    "Top 20 EDM": [
        { "name": "We Rave You", "reach": "30 million monthly", "label": "editorialagency", "color": "#2563EB", "vibe": "nightclub-laser", "pId": "d-vA8s_oFHg", "url": "https://weraveyou.com" },
        { "name": "Mixmag", "reach": "3 million monthly", "label": "imniatas v11", "color": "#E9110F", "vibe": "dj-turntable", "pId": "E9reH_x_y-8", "url": "https://mixmag.net" },
        { "name": "Earmilk", "reach": "1 million monthly", "label": "delicreations v11", "color": "#111111", "vibe": "milk-smoke", "pId": "H02zMhJ4T9c", "url": "https://earmilk.com" },
        { "name": "EDM.com", "reach": "600k monthly", "label": "staticrank v11", "color": "#111111", "vibe": "electronic-circuit", "pId": "W_XG_Gf_V7fM", "url": "https://edm.com" },
        { "name": "Your EDM", "reach": "600k monthly", "label": "bloggers._foodspot v11", "color": "#00A3FF", "vibe": "blue-glitch", "pId": "p5P-wI_w-R4", "url": "https://youredm.com" },
        { "name": "This Song Is Sick", "reach": "600k monthly", "label": "vidimatios v11", "color": "#FFD700", "vibe": "sick-party", "pId": "aJgK9f3-U7g", "url": "https://thissongissick.com" },
        { "name": "Resident Advisor", "reach": "600k monthly", "label": "alliterativebeatsvisuals", "color": "#C3FF00", "vibe": "industrial-party", "pId": "V_yXyA-8XyA", "url": "https://ra.co" },
        { "name": "iHeartRaves Blog", "reach": "400k monthly", "label": "---", "color": "#FF00FF", "vibe": "rave-lights", "pId": "vXz7w3B80yE" },
        { "name": "Dancing Astronaut", "reach": "300k monthly", "label": "vivithemaix v11", "color": "#E92C64", "vibe": "deep-space", "pId": "K_x_y-8XyA", "url": "https://dancingastronaut.com" },
        { "name": "EDMTunes", "reach": "250k monthly", "label": "editing._foodspot v11", "color": "#00D1FF", "vibe": "music-waves", "pId": "pG_y5j9XQW0", "url": "https://www.edmtunes.com" },
        { "name": "Run The Trap", "reach": "250k monthly", "label": "plugitindipublishing v11", "color": "#000000", "vibe": "trap-glitch", "pId": "n8mG9K_wUeU", "url": "https://runthetrap.com" },
        { "name": "FACT Magazine", "reach": "250k monthly", "label": "imniatas", "color": "#000000", "vibe": "modern-minimalist", "pId": "p31_w-yXyA", "url": "https://www.factmag.com" },
        { "name": "EDMManiac", "reach": "150k monthly", "label": "bloggers._foodspot v11", "color": "#FF1493", "vibe": "maniac-lights", "pId": "O_g9p_yXyA" },
        { "name": "Magnetic Magazine", "reach": "150k monthly", "label": "bloggers._foodspot v11", "color": "#111111", "vibe": "magnetic-field", "pId": "nO_g9p_yXyA", "url": "https://magneticmag.com" },
        { "name": "XLR8R", "reach": "150k monthly", "label": "imniatas", "color": "#000000", "vibe": "accelerator", "pId": "uPKY_p470d0", "url": "https://xlr8r.com" },
        { "name": "EDMIdentity", "reach": "100k monthly", "label": "staticrank", "color": "#00F0FF", "vibe": "id-card-glow", "pId": "W_XG_Gf_V7fM" },
        { "name": "Attack Magazine", "reach": "100k monthly", "label": "imniatas", "color": "#FF0000", "vibe": "red-alert", "pId": "H_yXyA_yXyA", "url": "https://www.attackmagazine.com" },
        { "name": "EDM Life", "reach": "90k monthly", "label": "bloggers._foodspot v11", "color": "#00FF00", "vibe": "city-night-life", "pId": "N_yXyA_yXyA" },
        { "name": "iEDM", "reach": "90k monthly", "label": "iedm", "color": "#FFD700", "vibe": "rave-fashion", "pId": "pG_y5j9XQW0" },
        { "name": "EDMProd (blog)", "reach": "90k monthly", "label": "bloggers._foodspot", "color": "#4A90E2", "vibe": "studio-laptop", "pId": "m_HRR_fV76fM" }
    ],

    "Big EDM Outlets": [
        { "name": "Your EDM", "reach": "600k monthly", "color": "#00A3FF", "vibe": "blue-glitch", "pId": "p5P-wI_w-R4", "url": "https://youredm.com" },
        { "name": "EDM.com", "reach": "600k monthly", "color": "#111111", "vibe": "electronic-circuit", "pId": "W_XG_Gf_V7fM", "url": "https://edm.com" },
        { "name": "Dancing Astronaut", "reach": "300k monthly", "color": "#E92C64", "vibe": "deep-space", "pId": "K_x_y-8XyA", "url": "https://dancingastronaut.com" },
        { "name": "EDMTunes", "reach": "250k monthly", "color": "#00D1FF", "vibe": "music-waves", "pId": "pG_y5j9XQW0", "url": "https://www.edmtunes.com" },
        { "name": "EDM Sauce", "reach": "100k monthly", "color": "#FF6B00", "vibe": "orange-glow", "pId": "O_g9p_yXyA", "url": "https://edmsauce.com" },
        { "name": "We Rave You", "reach": "30 million monthly", "color": "#2563EB", "vibe": "nightclub-laser", "pId": "d-vA8s_oFHg", "url": "https://weraveyou.com" },
        { "name": "Magnetic Magazine", "reach": "150k monthly", "color": "#111111", "vibe": "magnetic-field", "pId": "nO_g9p_yXyA", "url": "https://magneticmag.com" },
        { "name": "Mixmag", "reach": "3 million monthly", "color": "#E9110F", "vibe": "dj-turntable", "pId": "E9reH_x_y-8", "url": "https://mixmag.net" },
        { "name": "Run The Trap", "reach": "250k monthly", "color": "#000000", "vibe": "trap-glitch", "pId": "n8mG9K_wUeU", "url": "https://runthetrap.com" },
        { "name": "This Song Is Sick", "reach": "600k monthly", "color": "#FFD700", "vibe": "sick-party", "pId": "aJgK9f3-U7g", "url": "https://thissongissick.com" },
        { "name": "Earmilk", "reach": "1 million monthly", "color": "#111111", "vibe": "milk-smoke", "pId": "H02zMhJ4T9c", "url": "https://earmilk.com" },
        { "name": "FACT Magazine", "reach": "250k monthly", "color": "#111111", "vibe": "modern-minimalist", "pId": "p31_w-yXyA", "url": "https://www.factmag.com" },
        { "name": "XLR8R", "reach": "150k monthly", "color": "#111111", "vibe": "accelerator", "pId": "uPKY_p470d0", "url": "https://xlr8r.com" },
        { "name": "Resident Advisor", "reach": "600k monthly", "color": "#C3FF00", "vibe": "industrial-party", "pId": "V_yXyA-8XyA", "url": "https://ra.co" },
        { "name": "Attack Magazine", "reach": "100k monthly", "color": "#FF0000", "vibe": "red-alert", "pId": "H_yXyA_yXyA", "url": "https://www.attackmagazine.com" },
        { "name": "Acid Stag", "reach": "60k monthly", "color": "#FF4D00", "vibe": "acid-wash", "pId": "O_g9p_yXyA", "url": "https://acidstag.com" },
        { "name": "Groove Cartel", "reach": "60k monthly", "color": "#111111", "vibe": "cartel-office", "pId": "m_HRR_fV76fM", "url": "https://groovecartel.com" },
        { "name": "Noiseporn", "reach": "60k monthly", "color": "#FF0055", "vibe": "noise-visuals", "pId": "pG_y5j9XQW0", "url": "https://noiseporn.com" },
        { "name": "UFO Network", "reach": "60k monthly", "color": "#00FFC2", "vibe": "alien-glow", "pId": "vXz7w3B80yE", "url": "https://ufo-network.com" },
        { "name": "A&R Factory", "reach": "40k monthly", "color": "#111111", "vibe": "studio-gear", "pId": "N_yXyA_yXyA", "url": "https://anrfactory.com" }
    ],

    "EDM Name Only": [
        { "name": "EDMArmy", "reach": "10k monthly", "color": "#4B5320", "vibe": "military-digital", "pId": "nO_g9p_yXyA", "url": "https://edmarmy.com" },
        { "name": "EDMIdentity", "reach": "80k monthly", "color": "#00F0FF", "vibe": "id-card-glow", "pId": "W_XG_Gf_V7fM", "url": "https://www.edmidentity.com" },
        { "name": "EDMJoy", "reach": "60k monthly", "color": "#FF0080", "vibe": "joyful-vibes", "pId": "p5P-wI_w-R4", "url": "https://edmjoy.com" },
        { "name": "EDMManiac", "reach": "100k monthly", "color": "#FF1493", "vibe": "maniac-lights", "pId": "O_g9p_yXyA", "url": "https://edmmaniac.com" },
        { "name": "EDMNYC", "reach": "15k monthly", "color": "#111111", "vibe": "nyc-skyline", "pId": "YmX_K4eBwH8", "url": "https://edmnyc.com" },
        { "name": "EDMUnplugged", "reach": "15k monthly", "color": "#111111", "vibe": "acoustic-glow", "pId": "E9reH_x_y-8", "url": "https://edmunplugged.com" },
        { "name": "FinestOfEDM", "reach": "15k monthly", "color": "#FFD700", "vibe": "gold-luxury", "pId": "m_HRR_fV76fM", "url": "https://finestofedm.com" },
        { "name": "iEDM", "reach": "120k monthly", "color": "#FFD700", "vibe": "rave-fashion", "pId": "pG_y5j9XQW0", "url": "https://iedm.com" },
        { "name": "OneEDM", "reach": "45k monthly", "color": "#111111", "vibe": "minimal-one", "pId": "N_q_f_T-O_M", "url": "https://oneedm.com" },
        { "name": "EDM Den", "reach": "15k monthly", "color": "#111111", "vibe": "den-chill", "pId": "H02zMhJ4T9c", "url": "https://edmden.com" },
        { "name": "EDM MAG", "reach": "15k monthly", "color": "#111111", "vibe": "magazine-minimal", "pId": "p31_w-yXyA", "url": "https://edmmag.com" },
        { "name": "EDM World Magazine", "reach": "45k monthly", "color": "#2563EB", "vibe": "world-globe", "pId": "W_XG_Gf_V7fM", "url": "https://edmworldmagazine.com" },
        { "name": "Electronic Dance Magazine", "reach": "45k monthly", "color": "#111111", "vibe": "clinical-layout", "pId": "n8mG9K_wUeU", "url": "https://electronicdancemagazine.com" },
        { "name": "EDM Life", "reach": "60k monthly", "color": "#00FF00", "vibe": "city-night-life", "pId": "N_yXyA_yXyA", "url": "https://edmlife.com" },
        { "name": "EDMCult", "reach": "15k monthly", "color": "#111111", "vibe": "minimal-cult", "pId": "H_yXyA_yXyA", "url": "https://edmcult.com" },
        { "name": "DailyEDM", "reach": "10k monthly", "color": "#111111", "vibe": "daily-news", "pId": "pG_y5j9XQW0", "url": "https://dailyedm.com" },
        { "name": "EDMProd (blog)", "reach": "60k monthly", "color": "#4A90E2", "vibe": "studio-laptop", "pId": "m_HRR_fV76fM", "url": "https://www.edmprod.com/blog" }
    ],

    "Rave Name Only": [
        { "name": "RaveJungle", "reach": "100k monthly", "color": "#111111", "vibe": "jungle-night", "pId": "nO_g9p_yXyA", "url": "https://ravejungle.com" },
        { "name": "We Rave You", "reach": "30 million monthly", "color": "#2563EB", "vibe": "stadium-crowd", "pId": "d-vA8s_oFHg", "url": "https://weraveyou.com" },
        { "name": "Ravers Naturals", "reach": "5k monthly", "color": "#111111", "vibe": "organic-minimal", "pId": "p5P-wI_w-R4", "url": "https://raversnaturals.com" },
        { "name": "EDM Den (Rave Guide)", "reach": "5k monthly", "color": "#111111", "vibe": "guide-minimal", "pId": "E9reH_x_y-8", "url": "https://edmden.com/rave-guide" },
        { "name": "Rave Hackers", "reach": "10k monthly", "color": "#111111", "vibe": "code-matrix", "pId": "W_XG_Gf_V7fM", "url": "https://ravehackers.com" },
        { "name": "Rave Reviews", "reach": "10k monthly", "color": "#111111", "vibe": "stars-review", "pId": "H02zMhJ4T9c", "url": "https://ravereviews.net" },
        { "name": "RAVE! Magazin", "reach": "60k monthly", "color": "#111111", "vibe": "magazine-bold", "pId": "p31_w-yXyA", "url": "https://ravemagazin.de" },
        { "name": "The Rave Exchange", "reach": "15k monthly", "color": "#111111", "vibe": "exchange-minimal", "pId": "n8mG9K_wUeU", "url": "https://theraveexchange.com" },
        { "name": "Rave Report", "reach": "5k monthly", "color": "#111111", "vibe": "clinical-report", "pId": "pG_y5j9XQW0", "url": "https://ravereport.com" },
        { "name": "iHeartRaves Blog", "reach": "310k monthly", "color": "#FF00FF", "vibe": "neon-glow", "pId": "vXz7w3B80yE", "url": "https://www.iheartraves.com/blog" },
        { "name": "Devil Walking Blog", "reach": "5k monthly", "color": "#111111", "vibe": "aesthetic-minimal", "pId": "K_x_y-8XyA", "url": "https://devilwalking.com/blog" },
        { "name": "Raveraide Blog", "reach": "5k monthly", "color": "#111111", "vibe": "aid-minimal", "pId": "O_g9p_yXyA", "url": "https://raveraide.com/blog" },
        { "name": "The Rave Cave Blog", "reach": "5k monthly", "color": "#111111", "vibe": "cave-minimal", "pId": "uPKY_p470d0", "url": "https://theravecave.com/blog" },
        { "name": "RaveScoutr Blog", "reach": "3k monthly", "color": "#111111", "vibe": "scout-minimal", "pId": "N_yXyA_yXyA", "url": "https://ravescoutr.com/blog" },
        { "name": "Rave Bae Couture Blog", "reach": "3k monthly", "color": "#111111", "vibe": "couture-minimal", "pId": "pG_y5j9XQW0", "url": "https://ravebaecouture.com/blog" },
        { "name": "Rave On 1991", "reach": "3k monthly", "color": "#111111", "vibe": "vintage-minimal", "pId": "N_q_f_T-O_M", "url": "https://raveon1991.com" }
    ],
    "Indie & Rock": [
        { "name": "BrooklynVegan", "reach": "900k monthly", "color": "#111111", "vibe": "brooklyn-grit", "pId": "E9reH_x_y-8", "url": "https://www.brooklynvegan.com" },
        { "name": "The Line of Best Fit", "reach": "450k monthly", "color": "#111111", "vibe": "london-indie", "pId": "H02zMhJ4T9c", "url": "https://www.thelineofbestfit.com" },
        { "name": "Under the Radar", "reach": "225k monthly", "color": "#111111", "vibe": "radar-glow", "pId": "p31_w-yXyA", "url": "https://www.undertheradarmag.com" },
        { "name": "Indie Shuffle", "reach": "225k monthly", "color": "#111111", "vibe": "shuffle-vinyl", "pId": "V_yXyA-8XyA", "url": "https://www.indieshuffle.com" },
        { "name": "Obscure Sound", "reach": "165k monthly", "color": "#111111", "vibe": "obscure-studio", "pId": "K_x_y-8XyA", "url": "https://www.obscuresound.com" },
        { "name": "The Revue", "reach": "165k monthly", "color": "#111111", "vibe": "revue-theater", "pId": "pG_y5j9XQW0", "url": "https://www.therevue.ca" },
        { "name": "Wolf in a Suit", "reach": "165k monthly", "color": "#111111", "vibe": "wolf-aesthetic", "pId": "n8mG9K_wUeU", "url": "https://wolfinasuit.com" },
        { "name": "Indie is not a genre", "reach": "105k monthly", "color": "#111111", "vibe": "genre-minimal", "pId": "N_yXyA_yXyA", "url": "https://www.indieisnotagenre.com" },
        { "name": "Indie Rock Cafe", "reach": "60k monthly", "color": "#111111", "vibe": "cafe-acoustic", "pId": "uPKY_p470d0", "url": "https://indierockcafe.com" },
        { "name": "Ear to the Ground", "reach": "60k monthly", "color": "#111111", "vibe": "ground-roots", "pId": "m_HRR_fV76fM", "url": "https://eartothegroundmusic.co" },
        { "name": "Come Here Floyd", "reach": "60k monthly", "color": "#111111", "vibe": "floyd-vintage", "pId": "O_g9p_yXyA", "url": "https://comeherefloyd.com" },
        { "name": "Music Savage", "reach": "60k monthly", "color": "#111111", "vibe": "savage-minimal", "pId": "W_XG_Gf_V7fM", "url": "https://musicsavage.com" },
        { "name": "From the Strait", "reach": "60k monthly", "color": "#111111", "vibe": "strait-coastal", "pId": "vXz7w3B80yE", "url": "https://fromthestraitsound.com" },
        { "name": "The Indy Review", "reach": "60k monthly", "color": "#111111", "vibe": "indy-clinical", "pId": "nO_g9p_yXyA", "url": "https://theindyreview.com" },
        { "name": "Indie Boulevard", "reach": "60k monthly", "color": "#111111", "vibe": "boulevard-minimal", "pId": "p5P-wI_w-R4", "url": "https://indieboulevard.com" },
        { "name": "THE MIC MAG", "reach": "60k monthly", "color": "#111111", "vibe": "mic-studio", "pId": "pG_y5j9XQW0", "url": "https://themicmag.com" },
        { "name": "MP3 Hugger", "reach": "37k monthly", "color": "#111111", "vibe": "hugger-classic", "pId": "N_q_f_T-O_M", "url": "https://mp3hugger.com" },
        { "name": "Indie Obsessive", "reach": "37k monthly", "color": "#111111", "vibe": "obsessive-ivory", "pId": "H_yXyA_yXyA", "url": "https://indieobsessive.com" },
        { "name": "Jungle Indie Rock", "reach": "37k monthly", "color": "#111111", "vibe": "jungle-minimal", "pId": "v8S-UaE16C8", "url": "https://jungleindierock.com" },
        { "name": "The Indie Grid", "reach": "37k monthly", "color": "#111111", "vibe": "grid-clinical", "pId": "E9reH_x_y-8", "url": "https://www.theindiegrid.com" }
    ],

    "Hip-Hop Blogs": [
        { "name": "Complex (Music)", "reach": "30 million monthly", "color": "#000000", "vibe": "urban-monolith", "pId": "n8mG9K_wUeU", "url": "https://www.complex.com/music" },
        { "name": "HotNewHipHop", "reach": "15 million monthly", "color": "#FFC000", "vibe": "neon-gold", "pId": "E9reH_x_y-8", "url": "https://www.hotnewhiphop.com" },
        { "name": "HipHopDX", "reach": "10 million monthly", "color": "#CC0000", "vibe": "dx-matrix", "pId": "H02zMhJ4T9c", "url": "https://hiphopdx.com" },
        { "name": "XXL Mag", "reach": "5 million monthly", "color": "#ED1C24", "vibe": "print-legacy", "pId": "p31_w-yXyA", "url": "https://www.xxlmag.com" },
        { "name": "Rap-Up", "reach": "3 million monthly", "color": "#FF0080", "vibe": "pop-rap", "pId": "vXz7w3B80yE", "url": "https://www.rap-up.com" },
        { "name": "The Source", "reach": "3 million monthly", "color": "#111111", "vibe": "source-vault", "pId": "uPKY_p470d0", "url": "https://thesource.com" },
        { "name": "AllHipHop", "reach": "2 million monthly", "color": "#111111", "vibe": "street-minimal", "pId": "nO_g9p_yXyA", "url": "https://allhiphop.com" },
        { "name": "2DopeBoyz", "reach": "1 million monthly", "color": "#111111", "vibe": "vinyl-stacks", "pId": "V_yXyA-8XyA", "url": "https://2dopeboyz.com" },
        { "name": "DJBooth", "reach": "1 million monthly", "color": "#111111", "vibe": "studio-desk", "pId": "m_HRR_fV76fM", "url": "https://djbooth.net" },
        { "name": "Revolt TV", "reach": "5 million monthly", "color": "#000000", "vibe": "revolt-glitch", "pId": "N_q_f_T-O_M", "url": "https://www.revolt.tv" }
    ],
    "Country Blogs": [
        { "name": "Taste of Country", "reach": "2.2 million monthly", "color": "#F59E0B", "vibe": "honey-acoustic", "pId": "uPKY_p470d0", "url": "https://tasteofcountry.com" },
        { "name": "The Boot", "reach": "1.3 million monthly", "color": "#78350F", "vibe": "leather-boots", "pId": "H02zMhJ4T9c", "url": "https://theboot.com" },
        { "name": "Whiskey Riff", "reach": "900k monthly", "color": "#111111", "vibe": "whiskey-barrel", "pId": "E9reH_x_y-8", "url": "https://www.whiskeyriff.com" },
        { "name": "Saving Country Music", "reach": "450k monthly", "color": "#111111", "vibe": "rescue-mission", "pId": "p31_w-yXyA", "url": "https://savingcountrymusic.com" },
        { "name": "Holler", "reach": "450k monthly", "color": "#111111", "vibe": "mountain-hollow", "pId": "vXz7w3B80yE", "url": "https://holler.country" },
        { "name": "Nash Country Daily", "reach": "450k monthly", "color": "#111111", "vibe": "nashville-morning", "pId": "nO_g9p_yXyA", "url": "https://www.nashcountrydaily.com" },
        { "name": "Country Fancast", "reach": "225k monthly", "color": "#111111", "vibe": "fan-minimal", "pId": "m_HRR_fV76fM", "url": "https://countryfancast.com" },
        { "name": "Roughstock", "reach": "225k monthly", "color": "#111111", "vibe": "rough-grit", "pId": "n8mG9K_wUeU", "url": "https://www.roughstock.com" },
        { "name": "Country Music News Blog", "reach": "165k monthly", "color": "#111111", "vibe": "news-feed", "pId": "V_yXyA-8XyA", "url": "https://countrymusicnewsblog.com" },
        { "name": "Country Standard Time", "reach": "165k monthly", "color": "#111111", "vibe": "standard-time", "pId": "W_XG_Gf_V7fM", "url": "https://countrystandardtime.com" },
        { "name": "Twangville", "reach": "165k monthly", "color": "#111111", "vibe": "twang-guitar", "pId": "K_yXyA-8XyA", "url": "https://twangville.com" },
        { "name": "Country Music Life", "reach": "165k monthly", "color": "#111111", "vibe": "life-acoustic", "pId": "O_g9p_yXyA", "url": "https://countrymusiclife.com" },
        { "name": "Country Music Rocks", "reach": "165k monthly", "color": "#111111", "vibe": "rock-grit", "pId": "uPKY_p470d0", "url": "https://countrymusicrocks.net" },
        { "name": "Country Music People (CMP)", "reach": "165k monthly", "color": "#111111", "vibe": "people-minimal", "pId": "N_q_f_T-O_M", "url": "https://www.countrymusicpeople.com" },
        { "name": "Country Music News International", "reach": "165k monthly", "color": "#111111", "vibe": "intl-minimal", "pId": "pG_y5j9XQW0", "url": "https://www.countrymusicnewsinternational.com" },
        { "name": "The Daily Country", "reach": "60k monthly", "color": "#111111", "vibe": "daily-minimal", "pId": "v8S-UaE16C8", "url": "https://thedailycountry.com" },
        { "name": "Farce the Music", "reach": "60k monthly", "color": "#111111", "vibe": "satire-minimal", "pId": "N_yXyA_yXyA", "url": "https://farcethe-music.com" },
        { "name": "Galleywinter", "reach": "60k monthly", "color": "#111111", "vibe": "winter-acoustic", "pId": "p5P-wI_w-R4", "url": "https://galleywinter.com" },
        { "name": "CountryCentral", "reach": "60k monthly", "color": "#111111", "vibe": "central-hub", "pId": "YmX_K4eBwH8", "url": "https://countrycentral.com" },
        { "name": "Camp House Concerts Blog", "reach": "10k monthly", "color": "#111111", "vibe": "camp-acoustic", "pId": "H_yXyA_yXyA", "url": "https://camphouseconcerts.com/blog" }
    ],

    "Christian & Gospel": [
        { "name": "NewReleaseToday (NRT)", "reach": "900k monthly", "color": "#2563EB", "vibe": "modern-christian", "pId": "W_XG_Gf_V7fM", "url": "https://www.newreleasetoday.com" },
        { "name": "JesusFreakHideout", "reach": "450k monthly", "color": "#111111", "vibe": "hideout-glow", "pId": "H02zMhJ4T9c", "url": "https://www.jesusfreakhideout.com" },
        { "name": "CCM Magazine", "reach": "450k monthly", "color": "#2563EB", "vibe": "legacy-blue", "pId": "n8mG9K_wUeU", "url": "https://www.ccmmagazine.com" },
        { "name": "Christianity Today - Music", "reach": "450k monthly", "color": "#111111", "vibe": "editorial-ivory", "pId": "uPKY_p470d0", "url": "https://www.christianitytoday.com/music" },
        { "name": "The Christian Beat (TCB)", "reach": "225k monthly", "color": "#111111", "vibe": "beat-minimal", "pId": "pG_y5j9XQW0", "url": "https://thechristianbeat.org" },
        { "name": "Worship Leader Magazine", "reach": "165k monthly", "color": "#111111", "vibe": "worship-focus", "pId": "p31_w-yXyA", "url": "https://worshipleader.com" },
        { "name": "The Berean Test", "reach": "165k monthly", "color": "#111111", "vibe": "theological-lens", "pId": "N_yXyA_yXyA", "url": "https://thebereantest.com" },
        { "name": "AllBaze (Gospel)", "reach": "165k monthly", "color": "#111111", "vibe": "global-gospel", "pId": "N_q_f_T-O_M", "url": "https://allbaze.com" },
        { "name": "GospelMinds", "reach": "165k monthly", "color": "#111111", "vibe": "mind-minimal", "pId": "m_HRR_fV76fM", "url": "https://gospelminds.com" },
        { "name": "Praisejamzblog", "reach": "165k monthly", "color": "#111111", "vibe": "praise-vibes", "pId": "vXz7w3B80yE", "url": "https://praisejamzblog.com" },
        { "name": "Singing News Magazine", "reach": "165k monthly", "color": "#111111", "vibe": "southern-gospel", "pId": "p5P-wI_w-R4", "url": "https://singingnews.com" },
        { "name": "Gospelkey", "reach": "105k monthly", "color": "#111111", "vibe": "key-minimal", "pId": "nO_g9p_yXyA", "url": "https://gospelkey.com" },
        { "name": "Jesus Music Today", "reach": "105k monthly", "color": "#111111", "vibe": "daily-today", "pId": "W_XG_Gf_V7fM", "url": "https://jesusmusictoday.com" },
        { "name": "Hymns & Worship Songs", "reach": "60k monthly", "color": "#111111", "vibe": "hymn-minimal", "pId": "uPKY_p470d0", "url": "https://hymnsandworshipsongs.com" },
        { "name": "Add This Music", "reach": "60k monthly", "color": "#111111", "vibe": "playlist-clean", "pId": "m_HRR_fV76fM", "url": "https://addthismusic.com" },
        { "name": "GodsMusicToday.com", "reach": "60k monthly", "color": "#111111", "vibe": "radio-minimal", "pId": "N_q_f_T-O_M", "url": "https://godsmusictoday.com" },
        { "name": "Heaven's Metal Magazine", "reach": "60k monthly", "color": "#000000", "vibe": "heaven-grit", "pId": "H02zMhJ4T9c", "url": "https://heavensmetalmagazine.com" },
        { "name": "Keep The Faith", "reach": "60k monthly", "color": "#111111", "vibe": "faith-minimal", "pId": "p31_w-yXyA", "url": "https://keepthefaith.co.uk/music" },
        { "name": "Christian Music Mag", "reach": "60k monthly", "color": "#111111", "vibe": "mag-minimal", "pId": "pG_y5j9XQW0", "url": "https://christianmusicmag.com" },
        { "name": "Gospel Chapter", "reach": "10k monthly", "color": "#111111", "vibe": "chapter-minimal", "pId": "N_yXyA_yXyA", "url": "https://gospelchapter.com" }
    ],

    "Metal Blogs": [
        { "name": "Blabbermouth", "reach": "3 million monthly", "color": "#000000", "vibe": "metal-concert", "pId": "n8mG9K_wUeU" },
        { "name": "Metal Injection", "reach": "1.5 million monthly", "color": "#DF1F26", "vibe": "injection-site", "pId": "H02zMhJ4T9c" },
        { "name": "MetalSucks", "reach": "1 million monthly", "color": "#000000", "vibe": "industrial-sludge", "pId": "p31_w-yXyA" }
    ],

    "Spotify Matrix": [
        { "name": "10K Spotify", "reach": "$325", "color": "#1DB954", "vibe": "spotify-entry", "pId": "v8S-UaE16C8" },
        { "name": "15K Spotify", "reach": "$390", "color": "#1DB954", "vibe": "spotify-entry", "pId": "YmX_K4eBwH8" },
        { "name": "20K Spotify", "reach": "$490", "color": "#1DB954", "vibe": "spotify-entry", "pId": "pG_y5j9XQW0" },
        { "name": "25K Spotify", "reach": "$590", "color": "#1DB954", "vibe": "spotify-entry", "pId": "m_HRR_fV76fM" },
        { "name": "30K Spotify", "reach": "$690", "color": "#1DB954", "vibe": "spotify-entry", "pId": "p5P-wI_w-R4" },
        { "name": "40K Spotify", "reach": "$790", "color": "#1DB954", "vibe": "spotify-entry", "pId": "W_XG_Gf_V7fM" },
        { "name": "50K Spotify", "reach": "$890", "color": "#1DB954", "vibe": "spotify-entry", "pId": "uPKY_p470d0" },
        { "name": "60K Spotify", "reach": "$990", "color": "#1DB954", "vibe": "spotify-entry", "pId": "E9reH_x_y-8" },
        { "name": "75K Spotify", "reach": "$1,200", "color": "#1DB954", "vibe": "spotify-entry", "pId": "H02zMhJ4T9c" },
        { "name": "100K Spotify", "reach": "$1,500", "color": "#1DB954", "vibe": "spotify-entry", "pId": "vXz7w3B80yE" },
        { "name": "125K Spotify", "reach": "$1,875", "color": "#1DB954", "vibe": "spotify-entry", "pId": "v8S-UaE16C8" },
        { "name": "150K Spotify", "reach": "$2,250", "color": "#1DB954", "vibe": "spotify-entry", "pId": "YmX_K4eBwH8" },
        { "name": "200K Spotify", "reach": "$3,000", "color": "#1DB954", "vibe": "spotify-entry", "pId": "pG_y5j9XQW0" },
        { "name": "250K Spotify", "reach": "$3,550", "color": "#1DB954", "vibe": "spotify-entry", "pId": "m_HRR_fV76fM" },
        { "name": "500K Spotify", "reach": "$6,500", "color": "#1DB954", "vibe": "spotify-entry", "pId": "p5P-wI_w-R4" }
    ],

    "Press Packages": [
        { "name": "3 Articles (In-Network)", "reach": "$200", "color": "#3B82F6", "vibe": "press-in-network", "pId": "O_XpYyFHYoE" },
        { "name": "4 Articles (In-Network)", "reach": "$250", "color": "#3B82F6", "vibe": "press-in-network", "pId": "vXz7w3B80yE" },
        { "name": "5 Articles (In-Network)", "reach": "$300", "color": "#3B82F6", "vibe": "press-in-network", "pId": "YmX_K4eBwH8" },
        { "name": "4–7 Articles (Standard)", "reach": "$550", "color": "#3B82F6", "vibe": "press-standard", "pId": "pG_y5j9XQW0" },
        { "name": "6–10 Articles (Standard)", "reach": "$700", "color": "#3B82F6", "vibe": "press-standard", "pId": "m_HRR_fV76fM" },
        { "name": "10–15 Articles (Standard)", "reach": "$900", "color": "#3B82F6", "vibe": "press-standard", "pId": "p5P-wI_w-R4" },
        { "name": "3 Articles (Premium)", "reach": "$500", "color": "#3B82F6", "vibe": "press-premium", "pId": "W_XG_Gf_V7fM" },
        { "name": "4 Articles (Premium)", "reach": "$650", "color": "#3B82F6", "vibe": "press-premium", "pId": "uPKY_p470d0" },
        { "name": "6 Articles (Premium)", "reach": "$750", "color": "#3B82F6", "vibe": "press-premium", "pId": "E9reH_x_y-8" }
    ],

    "YouTube Matrix": [
        { "name": "10K YouTube", "reach": "$375", "color": "#FF0000", "vibe": "youtube-growth", "pId": "v8S-UaE16C8" },
        { "name": "20K YouTube", "reach": "$650", "color": "#FF0000", "vibe": "youtube-growth", "pId": "YmX_K4eBwH8" },
        { "name": "50K YouTube", "reach": "$1,200", "color": "#FF0000", "vibe": "youtube-growth", "pId": "vXz7w3B80yE" },
        { "name": "100K YouTube", "reach": "$1,500", "color": "#FF0000", "vibe": "youtube-growth", "pId": "m_HRR_fV76fM" }
    ],

    "SoundCloud Matrix": [
        { "name": "4K Streams", "reach": "$180", "color": "#FF5500", "vibe": "soundcloud-growth", "pId": "pG_y5j9XQW0" },
        { "name": "8K Streams", "reach": "$240", "color": "#FF5500", "vibe": "soundcloud-growth", "pId": "p5P-wI_w-R4" },
        { "name": "16K Streams", "reach": "$350", "color": "#FF5500", "vibe": "soundcloud-growth", "pId": "W_XG_Gf_V7fM" }
    ]
};
