import json
import os
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

def load_branding():
    with open('assets/branding.json', 'r') as f:
        return json.load(f)

def create_pdf(filename, title, content_list):
    brand = load_branding()
    
    doc = SimpleDocTemplate(f"output/{filename}", pagesize=LETTER)
    styles = getSampleStyleSheet()
    
    # Customize styles based on branding
    header_style = styles['Heading1']
    header_style.textColor = colors.HexColor(brand['colors']['primary'])
    
    body_style = styles['Normal']
    body_style.textColor = colors.HexColor("#333333")
    
    elements = []
    
    # Title Page
    elements.append(Paragraph(title, header_style))
    elements.append(Spacer(1, 12))
    
    for item in content_list:
        elements.append(Paragraph(item, body_style))
        elements.append(Spacer(1, 10))
    
    doc.build(elements)
    print(f"PDF generated: {filename}")

if __name__ == "__main__":
    test_content = [
        "This is a premium document generated by the Antigravity Document Factory.",
        "Inspired by the transcript, this PDF uses modular branding and automated scripting.",
        "Next steps include Excel automation and Slide Deck synthesis."
    ]
    create_pdf("Ai_Predictions_2026.pdf", "The Generative AI Landscape 2026", test_content)
